name: Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          java-version: 25
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build --no-watch-fs

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: artifact
          path: build/libs
